### ISSUE TITLE
Serve file from a private Azure storage account

### ISSUE THREAD

**Issue by tylernix** [jldeen/ghost-azurestorage#14]
Is this repo still maintained? 

From a security perspective, I would like to be able to serve my files from a private Azure storage account. The files would be served locally like they were stored on my website's server, yet retrieved from the private storage account on the backend using the storage connection string. That way, I could make my Azure Storage Account (and the files inside it) private instead of public for all to see. 

I can put together a pull request for this? I feel like it would help others who may be looking for the same functionality. I could use the config settings to toggle it on and off. options.serveAsLocalFile?

**Comment by jldeen** [comment]
Stale issue message

**Comment by tylernix** [comment]
I very much still want to contribute to this. Should I put together a pull request?

**Comment by juanramollino** [comment]
Happy to revive this @jldeen . I have a fresh version of this code ready for some scrutiny.

**Comment by jldeen** [comment]
Anyone who wants to contribute to these open issues is more than welcome - @juanramollino I saw you opened a few issues. Please submit any PRs you feel may be useful. This is no longer actively maintained as I no longer use Ghost personally and no longer work for Microsoft.
