### ISSUE TITLE
Hi - does this adapter still work?

### ISSUE THREAD

**Issue by ChristineTham** [jldeen/ghost-azurestorage#21]
I installed as per instructions, ghost started okay, But when I try to upload an image, I get "Request was rejected due to server error"

For what it's worth I created the Azure Storage account, a CDN, and then a public container, and referenced this container name in the config file. I also tried with without creating a container first and it doesn't work either.

**Comment by jldeen** [comment]
I just released an update and tested with Ghost 5. Adapter works but is no longer actively maintained. Closing this issue for now. If you continue to bump into problems, please open a new issue with the specific error you are seeing.
